-- =============================================================================
-- 0152 — Gazetteer Algérie (geo_places) : recherche de lieux tolérante
-- =============================================================================
-- Problème : Nominatim (OSM) ne tolère AUCUNE variante d'orthographe — un
-- client qui tape « Lekhmisse » ne trouve pas « Souk El Khemis » (Béjaïa).
-- Les toponymes algériens ont 3-4 graphies latines chacune (darija/kabyle).
--
-- Solution : table locale des localités (import GeoNames DZ + ajouts manuels)
-- avec DOUBLE matching :
--   1. trigram word_similarity sur `search_text` (nom + noms alternatifs FR/AR
--      normalisés minuscules sans accents) → fautes de frappe classiques ;
--   2. « squelette consonantique » `skel` (voyelles/espaces/apostrophes
--      retirées, doublons collapsés, entrées séparées par |) → variantes de
--      translittération : lekhmisse → lkhms ⊂ sklkhms (souk el khemis).
--
-- RPC `search_geo_places(q, lat, lng, limit)` : score = similarité + bonus de
-- proximité (biais position client) + bonus population. Lecture seule, exposée
-- à anon/authenticated (résultats publics par nature).
--
-- Ajouts manuels : INSERT sans geoname_id (id identity). L'import GeoNames ne
-- touche que les lignes geoname_id IS NOT NULL (ré-import idempotent).
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.geo_places (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  geoname_id BIGINT UNIQUE,
  name TEXT NOT NULL,
  wilaya TEXT,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  feature_code TEXT,
  population INTEGER NOT NULL DEFAULT 0,
  search_text TEXT NOT NULL,
  skel TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_geo_places_search_trgm
  ON public.geo_places
  USING gin (search_text extensions.gin_trgm_ops);

ALTER TABLE public.geo_places ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS geo_places_read ON public.geo_places;
CREATE POLICY geo_places_read ON public.geo_places
  FOR SELECT TO anon, authenticated USING (true);

-- ---------------------------------------------------------------------------
-- Normalisation côté SQL (parité avec scripts/import-geonames-dz.mjs) :
-- minuscules sans accents → ne garder que lettres/chiffres → retirer les
-- voyelles latines → collapser les répétitions.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.geo_skeleton(p TEXT)
  RETURNS TEXT
  LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $$
  SELECT regexp_replace(
    regexp_replace(
      regexp_replace(public.f_unaccent(lower(p)), '[^[:alnum:]]', '', 'g'),
      '[aeiouy]', '', 'g'),
    '(.)\1+', '\1', 'g')
$$;

CREATE OR REPLACE FUNCTION public.search_geo_places(
  p_q TEXT,
  p_lat DOUBLE PRECISION DEFAULT NULL,
  p_lng DOUBLE PRECISION DEFAULT NULL,
  p_limit INT DEFAULT 6
)
RETURNS TABLE (
  name TEXT,
  wilaya TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  score REAL
)
LANGUAGE sql STABLE
SET search_path = public, extensions
AS $$
  WITH q AS (
    SELECT public.f_unaccent(lower(trim(p_q))) AS t,
           public.geo_skeleton(p_q) AS sk
  )
  SELECT g.name, g.wilaya, g.lat, g.lng,
    (
      greatest(
        extensions.word_similarity((SELECT t FROM q), g.search_text),
        -- correspondance par squelette = très bon signal de translittération
        CASE WHEN length((SELECT sk FROM q)) >= 3
                  AND g.skel LIKE '%' || (SELECT sk FROM q) || '%'
             THEN 0.62 ELSE 0 END
      )
      -- bonus proximité : 0.2 à 0 km, ~0.1 à 50 km, ~0.03 à 250 km
      + CASE WHEN p_lat IS NOT NULL AND p_lng IS NOT NULL THEN
          0.2 / (1.0 + sqrt(power((g.lat - p_lat) * 111.0, 2)
                          + power((g.lng - p_lng) * 93.0, 2)) / 50.0)
        ELSE 0 END
      -- bonus population : les villes connues avant les lieux-dits homonymes
      + least(0.06, ln(1 + g.population) / 200.0)
    )::real AS score
  FROM public.geo_places g
  WHERE extensions.word_similarity((SELECT t FROM q), g.search_text) >= 0.34
     OR (length((SELECT sk FROM q)) >= 3
         AND g.skel LIKE '%' || (SELECT sk FROM q) || '%')
  ORDER BY score DESC
  LIMIT greatest(1, least(coalesce(p_limit, 6), 12))
$$;

GRANT EXECUTE ON FUNCTION public.search_geo_places(TEXT, DOUBLE PRECISION, DOUBLE PRECISION, INT)
  TO anon, authenticated;
